### ISSUE TITLE
Enhancement: logging addon

### ISSUE THREAD

**Issue by pavoroby** [topkecleon/telegram-bot-bash#104]
It would be a good idea to implement the forwarding of messages received by the bot not from administrators.
The message may contain the return address of the author of the message. It would be great to send these messages without notifications "disable_notification=1"

**Comment by gnadelwartz** [comment]
do you think about every message recieved, regardless its a command or some silly Text, should be forewarde to a specific person?

or its more about a notification if a specific command is used by a non admin?

**Comment by pavoroby** [comment]
I would like to have this setting in the code.  I would like to have a choice of logging level.  For example: 0 - nothing, 1 - report sometimes, 2 - full duplication of all incoming messages to the administrators address

**Comment by gnadelwartz** [comment]
ok, I understand, i'll go to jmplement a logging addon in the next Version lije this

- no logging by default
- level 1 log private messages
- level 2 log also public chats
- level 3 log and forward every message

level 3 may lead to blocking the bot by telegram ... https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this

**Comment by gnadelwartz** [comment]
I implement more logging in the current dev Version, regularly only basic logging of current activities.
with debug all incomming and outgoing message are logged.

this is not exactly what you are asking for but you can see everything what's seen and sent by the bot

**Comment by gnadelwartz** [comment]
in addition I added an example how to do logging for users and/or chats https://github.com/topkecleon/telegram-bot-bash/commit/30a72eb853ac18832e8f13360ea43afe30b83957
