### ISSUE TITLE
How to search sql database?

### ISSUE THREAD

**Issue by Azat868** [topkecleon/telegram-bot-bash#106]
**I used to**
```bash
fraze=$(echo $MESSAGE | cut -c 6- |  tr -dc '[:alnum:] ' | tr '[:upper:]' '[:lower:]')
IFS1="$IFS"; IFS="|"; S=$(sqlite3 /home/base.sql "SELECT * FROM one WHERE ( LOWER (Name) LIKE '%$fraze%' )") ; A=( $S ); IFS="$IFS1"
send_action "${CHAT[ID]}" "typing" 
```

Maybe you know a better, safer database search?

**Comment by Azat868** [comment]
mycommands.sh
```bash
"wiki"*) # logic for /process is done in process_message 
result="$(process_message "$MESSAGE")"
send_normal_message "${CHAT[ID]}" "$result"
			;;
```
etc
```bash
process_message() {
	IFS1="$IFS"; IFS="|"; Sert="$(sqlite3 /new19.sql "SELECT * FROM one WHERE ( LOWER (Name) LIKE '%$1%' )")" ; A=( $S ); IFS="$IFS1" 
aa=$(echo "${A[1]}" |   sed 's|</li>||g' | sed 's|<li>||g' | sed 's|</ul>||g' | sed 's|<ul>||g' | sed 's|*||g' | sed 's|</b>|*|g' |sed 's|<b>|*|g')
echo "You $aa and $1 in ${A[1]}"
}
```
I write bot:

> wiki device

Bot returns me:

>You  and device   in

response from sql ($aa var) is not displayed. I write the search word bypassing the wrapper:
```bash
process_message() {
	IFS1="$IFS"; IFS="|"; Sert="$(sqlite3 /new19.sql "SELECT * FROM one WHERE ( LOWER (Name) LIKE '%devicename%' )")" ; A=( $S ); IFS="$IFS1" 
aa=$(echo "${A[1]}" |   sed 's|</li>||g' | sed 's|<li>||g' | sed 's|</ul>||g' | sed 's|<ul>||g' | sed 's|*||g' | sed 's|</b>|*|g' |sed 's|<b>|*|g')
echo "You $aa and $1 in ${A[1]}"
}
```
Note: 
```bash
 ( LOWER (Name) LIKE '%devicename%' )")" 
```
I wrote in advance a phrase to search in the request body sql.
I write bot:

> wiki

Bot returns me:

>You  price 100 cents and devicename   in price 100 cents

If you manually write to the function "search query" it works. Bot returns the search result. But if you resort to input arguments:
```bash
process_message "$MESSAGE"
etc
$1
```
telegram-bot-bash not work. Why? If I do something wrong please tell me. I'm new to bash. On the old version telegram-bot-bash everything worked for me (see the code above). The new version does not work.

**Comment by gnadelwartz** [comment]
For me it looks ok, but I'm not SQL expert and don't know what's allowed characters in your query.
IMHO it is a good idea to block worst things like ';' '||' '--' 'AND' 'load_extension' ...

serach for "sqlite sql injection"
