### ISSUE TITLE
Enhancement: sendMediaGroup

### ISSUE THREAD

**Issue by Azat868** [topkecleon/telegram-bot-bash#107]
```bash
Mediagroup=$URL'/sendMediaGroup'
```
https://core.telegram.org/bots/api/#sendmediagroup
The bot lacks an important sending method: sending an album. I understand that this affects a big update, I did this:
```bash
commands.sh
curl -s -F media='[{"type":"photo","media":"'$image1'"},{"type":"photo","media":"'$image2'"},{"type":"photo","media":"'$image3'"},{"type":"photo","media":"'$image4'"},{"type":"photo","media":"'$image5'"}]' -H "Content-Type:multipart/form-data" "https://api.telegram.org/bot<token>/sendMediaGroup?chat_id=${CHAT[ID]}"
```
In the old version telegram-bot-bash it works. Now it does not work. How to fix?

**Comment by gnadelwartz** [comment]
hm, from first view it should work, what s the answer given Back by telegram?

nevertheless it seems to be a nice feature, ill try to implement it in the next Version.

**Comment by Azat868** [comment]
I usually run scripts in the terminal. And I see the answer. Here I do not know how to watch log-answers. How to do it?

**Comment by Azat868** [comment]
{"ok":false,"error_code":400,"description":"Bad Request: wrong remote file id specified: Wrong character in the string"}
Im fix, thx

**Comment by gnadelwartz** [comment]
@Azat868 based on your example JSON I was able to implement a first working version of send_album https://github.com/topkecleon/telegram-bot-bash/commit/e3151626c0f12a605fc38340b0be466dc7c1fa6a

```bash
usage: send_album  chat  mage1  image2 ... imageN

# your example from above will look like:
send_album  "${CHAT[ID]}"  "$image1"   "$image2" "$image3"   "$image4"

```

If you know how to upload multiple files for/with sendMediaGroup feel free to provide some examples ...
