### ISSUE TITLE
How to send smiles?

### ISSUE THREAD

**Issue by Azat868** [topkecleon/telegram-bot-bash#108]
```bash
send_markdown_message "${CHAT[ID]}" "🧐"
```
In the old version, I just copied smilies in commands.sh. Now in the new version, if you insert a smile in the native version, it will not go. How to send smiles? Unicode smiles didn't work in the previous version ...

**Comment by gnadelwartz** [comment]
Hi, I tested today, for me it works:

```

source bashbot.sh
send_normal_message $(cat "botadmin") '🧐'
send_markdown_message $(cat "botadmin") '🧐'
```

![Bildschirmfoto vom 2019-06-24 10-16-22](https://user-images.githubusercontent.com/4593242/60002581-336c9f80-9669-11e9-8a16-f19f2b6ac44e.png)
