### ISSUE TITLE
Can't get interactive to work

### ISSUE THREAD

**Issue by jesusvpct** [topkecleon/telegram-bot-bash#110]
I can't get to work the interactive question sample. It sends all the text but it's not waiting to get any response from the user. What I'm missing? Thanks.

![Screenshot_20191116_213743](https://user-images.githubusercontent.com/5315258/68998964-6c780b80-08b9-11ea-8cdb-bc56004dde7d.png)

**Comment by gnadelwartz** [comment]
Hi, do you use the latest Version?

I'll test it ...

**Comment by massive91** [comment]
I confirm that, on the latest version there is a bug with interactive chat

**Comment by gnadelwartz** [comment]
Has anyone of you found working version for Interactive?

**Comment by gnadelwartz** [comment]
IMHO the problem with interactive was that the pipe disappeared and no user input was sent to script.
I reworked start_proc, this will hopefully fix this also https://github.com/topkecleon/telegram-bot-bash/commit/3f85134d2fb9b4c3583e9efae8c521d3821cbfa6

**Comment by gnadelwartz** [comment]
interactive scripts are working again, but you must read user input from $3 instead from stdin, see https://github.com/topkecleon/telegram-bot-bash/blob/develop/doc/3_advanced.md#interactive-chats

**Comment by RandomUsN** [comment]
Interactive scripts are not working again for latest version 1.1. Please check.
Debian 10
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Used scripts/interactive.sh and examples/question.sh
