### ISSUE TITLE
New bug sending files

### ISSUE THREAD

**Issue by amontigita** [topkecleon/telegram-bot-bash#111]
Since a few days ago,  I was not able to get files like pics.
I discovered that this line in bashbot.sh was blocking it:
echo "$file" | grep -qE $FILE_REGEX || return 
to be changed in the following:
echo "$file" | grep -qE "$FILE_REGEX" || return 

I do not why it stopped working, I did not made any change to "commands.sh", 
but it did.

**Comment by gnadelwartz** [comment]
Thanks for reporting, this is indeed a bug.
If its also in the latest version I'll fix it

Am 26. November 2019 17:29:03 schrieb amontigita <notifications@github.com>:

**Comment by amontigita** [comment]
Well, good then.
I love that  software. It handles my home automation, with my raspi. It worked for months flawlessly-

Andrea Monti-Guarnieri

On Tue, Nov 26, 2019 at 5:54 PM Kay Marquardt <notifications@github.com<mailto:notifications@github.com>> wrote:
Thanks for reporting, this is indeed a bug.
If its also in the latest version I'll fix it

Am 26. November 2019 17:29:03 schrieb amontigita <notifications@github.com<mailto:notifications@github.com>>:

**Comment by gnadelwartz** [comment]
it's indeed also in the newest Version, I'll fix it with the nex release.

BTW: as you find the line in bashbot.sh, it seems you are using an older version of bashbot.
you may consider upgrading because of many enhancements and security fixes

the bug you found is in modules/sendmessage in the current version.

**Comment by gnadelwartz** [comment]
HI, I have to revert the change because with quotes the regex is compared as string, not regex.

remember if you want to allow only files from e.g. **"/home/user/test/*"** the regex should be **"^/home/user/test/.*"**
