### ISSUE TITLE
/info not working

### ISSUE THREAD

**Issue by jrettsch** [topkecleon/telegram-bot-bash#112]
missing `"${CHAT[ID]}"` in line 80 of commands.sh

```
send_markdown_message "${bashbot_info}"
send_markdown_message "${CHAT[ID]}" "${bashbot_info}"
```

**Comment by gnadelwartz** [comment]
fixed https://github.com/topkecleon/telegram-bot-bash/commit/b84ab57f6f0c4d513c99c5d7d26a3df3cb917933 for next release
