### ISSUE TITLE
/info always returns a date, not $bashbot_info

### ISSUE THREAD

**Issue by devilmind81** [topkecleon/telegram-bot-bash#113]
Hi,
I have deployed the latest version of the bot.
I'm able to run it well and I'm able to create new commands.
I have noticed that /info command always return the current date and time.
I'm not able to display the bashbot_info on the /info directive.
Is it overrided by default from another value? I cannot find the way to fix it!

Thanks in advance.

**Comment by gnadelwartz** [comment]
hi, I assume you have implemented you command's in 'commands.sh' because the date output from the info command overwrite example in 'mycommands.sh'

``` bash
		##########
		# command overwrite examples
		'/info'*) # output date in front of regular info
			send_normal_message "${CHAT[ID]}" "$(date)"
			return 0

```

as described in developer chapter, you should do all changes in 'mycommands.sh'.
if you don't use mycommands, delete it.

**Comment by devilmind81** [comment]
My issue, you are right.
Thank you!
