### ISSUE TITLE
Replace #!/bin/bash with #!/usr/bin/bash

### ISSUE THREAD

**Issue by alohawolf** [topkecleon/telegram-bot-bash#120]
I'm attempting to get the bot running on OSX, one issue I found was that the version of bash included on OS X is ancient (bash 3.2.57) which has issues with the command arguments in declare for running the bot, because of this, its common to install a newer bash than the operating ships with. By hardcoding to /bin/bash the application becomes less portable.

**Comment by gnadelwartz** [comment]
may be I'll change the shebang to `#! /usr/bin/env bash`

see https://stackoverflow.com/questions/21612980/why-is-usr-bin-env-bash-superior-to-bin-bash

can you confirm it's working?

**Comment by gnadelwartz** [comment]
like Mac OS there may embedded systems out there not supporting env and breaking on update.
do I provided an example script to convert from /bin/bash to /usr/bin/env ...

see https://github.com/topkecleon/telegram-bot-bash/commit/96fda449b53108bf002cb2a234a8525d5158485c

**Comment by alohawolf** [comment]
It's not just MacOS, neither BSD ships bash in /bin/bash.

That said, I tested this, the script you provided expect me to tell it what scripts I want to convert, if I'm someone just starting out, how would I know which scripts need converting?

**Comment by gnadelwartz** [comment]
usually only bashbot.sh and json.sh/json.sh, nevertheless just do

./bash2env *.sh */*.sh

as explained in the docs now, we will stay for security with the fixed path, as the portable solution uses the first bash in PATH witch may a malicious one ...
