### ISSUE TITLE
start_bot nextsleep variable definition bad syntax

### ISSUE THREAD

**Issue by vevsvevs** [topkecleon/telegram-bot-bash#134]
**Describe the bug**
I believe `nextsleep="100" :` in the `start_bot` function contains some unneeded `:` :)

**Comment by gnadelwartz** [comment]
fixed in dev https://github.com/topkecleon/telegram-bot-bash/commit/3d760b331952deaf03ba05ae5d5b9bef3bd098dd

**Comment by gnadelwartz** [comment]
now also in master https://github.com/topkecleon/telegram-bot-bash/commit/48f314eaaa5d0416857260ca2440e717c47773fc

thanks for reporting
