### ISSUE TITLE
Only let me to send about 5/6 messages per second

### ISSUE THREAD

**Issue by magixmagixmagix** [topkecleon/telegram-bot-bash#145]
Hi, I need to send a lot of messages inside 10seconds, and telegram-bot-bash only let me send about 6 messages (send_normal_message) per second. (I've searched about telegram API, and telegram let 100 calls/sec)
Is an issue? or I can adjust it?

(sorry if isn't the place to write this message, but I can't send PM's to contributors)

Thanks beasts!

**Comment by gnadelwartz** [comment]
his s not a limit of the bot, there may several reasons:

- depending on your hardware power it take some time to send a message 
- telegram has different limits: [FAQ](https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-avoid-this)
   -  30 msgs per second max, depeding on your behavior also less
   - 20 msgs per minute to the same group or user
   - other limits not explained
- if you hit telegram internal limits you get errors responses from telegram
- if you hit limits to often, telegram will block your bot

**Comment by magixmagixmagix** [comment]
A lot of thanks for the quick and detailed response @gnadelwartz 

I will enable DEBUG and I will do more research work

Thanks again! 🙏

**Comment by gnadelwartz** [comment]
send messages in parallel:

```bash
send_normal_message chat1 message1 &
send_normal_message chat2 message2 &
send_normal_message chat3 message3 &
send_normal_message chat4 message4 &
send_normal_message chat5 message5 &
send_normal_message chat6 message6 &
send_normal_message chat7 message7
wait # after 5-10 messages wit to finish to not overload
```

**Comment by magixmagixmagix** [comment]
Isn't hardware problem, so parallel messages will work,
I will test it! A LOT of thanks again beast!❤😍🙏

**Comment by gnadelwartz** [comment]
the fastest way to send a text message without overhead is:

`sendJson "${chat}" "\"text\":\"${message}\"" "${URL}/sendMessage" `

may be I should add a tips and tricks section ;-)

**Comment by magixmagixmagix** [comment]
Thanks again! 📝noted
I think it's a very good idea tips and tricks section, starting with this information that you just told me 🤩
👏
