### ISSUE TITLE
Delete mycommands.sh from git

### ISSUE THREAD

**Issue by dcoomber** [topkecleon/telegram-bot-bash#151]
The version of `mycommands.sh` in both the `master` and `develop` branches is a copy of `mycommands.sh.dist`.

Should the file `mycommands.sh` not be deleted from git and be added to `.gitignore`?  (I'm happy to do this and submit a PR for each branch, but don't want to overstep boundaries.

**Comment by gnadelwartz** [comment]
the .dist files are created when a release is done by dev/make-distribution.sh and should be only available after installation or update from zip tar.gz file. it's done thus way to not overwrite already modified files on update.

but you are right,  there should be a *.dist in .gitignore

**Comment by gnadelwartz** [comment]
may be I should explain more clear that installation and updates should be done from zip/tar.gz and using git only for development only

https://github.com/topkecleon/telegram-bot-bash/blob/master/doc/0_install.md#update-bashbot

**Comment by gnadelwartz** [comment]
done: c2a110a74d8b80dce0d29939830904f8d61d19ef
