### ISSUE TITLE
Ineractive scripts not working as expected

### ISSUE THREAD

**Issue by RandomUsN** [topkecleon/telegram-bot-bash#159]
Interactive scripts are not working again for latest version 1.1. Please check.
Debian 10
GNU bash, version 5.0.3(1)-release (x86_64-pc-linux-gnu)
Used scripts/interactive.sh and examples/question.sh

**Comment by gnadelwartz** [comment]
related to #158 , will check when issue is resolved

**Comment by RandomUsN** [comment]
[https://github.com/topkecleon/telegram-bot-bash/issues/158](url) it was fixed, but it did not help fix the problem with interactive scripts.

**Comment by gnadelwartz** [comment]
I'll investigate

**Comment by gnadelwartz** [comment]
I hvae the strange effect that even in a private chat and privacy disbaled the updates sent by telegram only contains commands, but not regular text not starting with /.

May be telgram changed the behaivoir, so inetractive scripts ca not wort anymore. I'll investigate more on it

**Comment by gnadelwartz** [comment]
OK found the problem,  a workaround for a special use case was the problem ...

**Comment by gnadelwartz** [comment]
fixed https://github.com/topkecleon/telegram-bot-bash/pull/161/commits/975d0147f4412d45b9d34901786b44e80215d397
