### ISSUE TITLE
warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)

### ISSUE THREAD

**Issue by jonashaag** [topkecleon/telegram-bot-bash#163]
I get this when running bashbot:

```
bashbot.sh: line 62: warning: setlocale: LC_ALL: cannot change locale (C.UTF-8)
```

I'm on Manjaro Linux

**Comment by gnadelwartz** [comment]
looks like you have not installed/activated "most universal" c.UTF-8 locale on your system, change it to your prefered existing locale or  activate c.utf-8:

https://wiki.manjaro.org/index.php?title=Locale

**Comment by gnadelwartz** [comment]
in addtion I'll add a warning about non existing C locale and rederict the error message

**Comment by gnadelwartz** [comment]
done: https://github.com/topkecleon/telegram-bot-bash/commit/10c104d471ad0cea9ef35f33407172d081fd505e
