### ISSUE TITLE
Detection of unicode support

### ISSUE THREAD

**Issue by rlegene** [topkecleon/telegram-bot-bash#164]
I'm running bash version 5, so the message surprised me a bit. It turns out the lacking conversion of certain unicode codepoints depends on the locale settings. Setting LANG to UTF-8 makes it pass this test.

```bash
$ ./bashbot.sh 
Warning: Unicode '\uxxxx' seems not supported, install a more current bash.
Available commands: start, stop, status, help, init, stats, broadcast, suspendback, resumeback, killback
$ LANG=en_US.UTF-8 ./bashbot.sh
Available commands: start, stop, status, help, init, stats, broadcast, suspendback, resumeback, killback
```

**Comment by gnadelwartz** [comment]
thanks for the hint. what's your default locale?

**Comment by gnadelwartz** [comment]
https://github.com/topkecleon/telegram-bot-bash/commit/824cf137d9be40d763def5f296dfab8b1543b7ac fixed
