### ISSUE TITLE
Why telegram-bot-bash is too slow respond?

### ISSUE THREAD

**Issue by manuksia** [topkecleon/telegram-bot-bash#180]
I have tried many times to run my telegram-bot-bash and sent some message to my bot. But the respond was too slow .

**Comment by gnadelwartz** [comment]
Bashbot is polling telegram for updates in default mode and uses adaptive waiting to avoid polling telegram to often.
Try to set 'BASHBOT_SLEEP' to '1' before starting bashbot, this set the maximum wait time to 1s,  e.g.:

```bash
BASHBOT_SLEEP=1
./bashbot.sh start

```
