### ISSUE TITLE
Send file content or command output

### ISSUE THREAD

**Issue by nzurita** [topkecleon/telegram-bot-bash#181]
Hello, I'd like to use bashbot to send command outputs or command logs (the content of the log, not the attached file).

I've tryed these commands:
```
    $echo "Hello" | telegram-bot-bash/bin/send_message.sh "123456"
    $telegram-bot-bash/bin/send_message.sh "123456" < file.log
    $telegram-bot-bash/bin/send_file.sh "123456" file.log "Your log"
```
None of them seem to work, is there a way to do it?

Thank you.

**Comment by gnadelwartz** [comment]
does `send_message-sh BOTADMIN "test"` send test to you telfgram acount?

If yes: use  `send_message-sh BOTADMIN "$(echo "hello")"` or `send_message-sh BOTADMIN "$(<file.log)"`

If no: run `bashbot.sh init` and try again

Nevertheless I'll add the usual '-' as read from STDIN in next release

**Comment by nzurita** [comment]
It did work, thank you (replacing BOTADMIN by chat number, I was it's what you meant)
