### ISSUE TITLE
How to determine the type of sent message?

### ISSUE THREAD

**Issue by Azat868** [topkecleon/telegram-bot-bash#199]
The user can send photos, videos, music, sticker etc. By what variables in the bot can you determine that different types of messages were sent?

```
User: send audio
Bot: Great music!
User: send pdf file
Bot: Good file!
```

**Comment by Azat868** [comment]
@gnadelwartz thx
But I still can't. How to get images in question mode?
![изображение](https://user-images.githubusercontent.com/29046741/226877829-3c76d32c-6e77-4ab4-8163-ddd8c526fcdc.png)

**Comment by gnadelwartz** [comment]
OK, this is a little more tricky as scrípts reads new messages from STDIN.

Solution may to add some special special processing in mycommands.sh.
Try to add something like this after the MESSAGE processing in your mycommands.sh (untestet!)

```bash
        case "${MESSAGE}" in
                ##################
                # example commands, replace them by your own
#.... [ comands removed, exampel code starts behind esac] ....

         esac
     
        # example URLS processing for scripts
        for KEY in "${!URLS[@]}"
        do
                [ "${URLS[KEY]}" != "" ] && MESSAGE = "${MESSAGE} my${KEY}startshere ${URLS[KEY]}"
        done
```

if a file is recieved you will read something like this from STDIN in your script

    User sends picture -> myPHOTOstartshere /path/to/photo  
    User sends audio -> myAUDIOstartshere /path/to/music

**Comment by Azat868** [comment]
@gnadelwartz thx you!
May be you know, where check file size before download? ${URLS[DOCUMENT]} , because user can send 2gb files, how to district?

**Comment by gnadelwartz** [comment]
yes, download ever random big file seems a bad Design decision, I'll limit this in next releases to files of a max size. bigger files must downloaded manually then

**Comment by Azat868** [comment]
photo="${URLS[PHOTO]}"
		docs="${URLS[DOCUMENT]}"
		if [ -z "$photo" ] ; then
               	if [ -z "$docs" ] ; then
