### ISSUE TITLE
Bot does not parse multiline messages

### ISSUE THREAD

**Issue by danog** [topkecleon/telegram-bot-bash#21]
Due to the way it parses the output of JSON.sh the bot cannot parse incoming multiline messages (only the first line will be recieved).
This can be fixed by altering the way we parse the output of JSON.sh, and I'm going to fix this ASAP.

**Comment by iicc1** [comment]
I managed to solve it doing this:
	
`MESSAGE=$(echo "$res" | egrep '\["result",0,"message","text"\]' | cut -f 2 | cut -d '"' -f 2 | ascii2uni -a U -q)`
         `MESSAGE=$(printf "$MESSAGE")`

**Comment by iicc1** [comment]
I noticed that this also fixes sending `fixedsys` markdown style when resending through the bot, resends correctly most symbols and accents (before appeared its hex code) and can resend some emoji. But most of emoji crashes.

**Comment by danog** [comment]
I've got an interesting conception of ASAP.
