### ISSUE TITLE
Keyboard: several buttons in a row

### ISSUE THREAD

**Issue by sprnza** [topkecleon/telegram-bot-bash#24]
Hi there!
Thank you very much for your job! It makes telegram bot very easy to adopt!
Just a little question: is there a way to send several buttons in one row in a custom keyboard?
I know that it must be an array of arrays of lines that looks like 
`[["top left","top right"],["Bottom left","Bottom right"]]`
I've tried all possible combinations with no luck. Loking into bashbot.sh code  seems like it's impossible at all. Am I right?

**Comment by danog** [comment]
It actually is possible, you just have to implement a loop that creates the nested arrays for the rows and then a sub loop that creates the buttons for these sub arrays.

**Comment by sprnza** [comment]
Hi Danog! Thanks for the reply!
Yeah I see my question is missing some details :) 
I wonder how to "echo" the array of arrays to have it sent correctly? 
IFS is being set to "\"" so I try to do
`echo "Text mykeyboardstartshere \""tl", "tr"\" \"Cancel\""`
as I see the parameters are being wrapped by [] at string #208 (bashbot.sh) and then they alltogether is being wrapped by another square brackets at at string #211 (bashbot.sh) so I expect my keyboard array to be
`[["tl", "tr"],[Cancel]]`
to have two buttons in the top row.
But I see just two rows with "tl, tr" in the top one (without quotes).
I've tried to change IFS to ' and make my string as
`echo "Text mykeyboardstartshere '"tl", "tr"' 'Cancel'"`
but I still get the same two buttons. So the quotes must be escaped. If I do
`echo "Text mykeyboardstartshere '\"tl\", \"tr\"' 'Cancel'"`
I don't get in a chat anything. Plus I'm not experienced enough to know how to debug what is being sent to the API in this case  :)
Hope it's became clearer.

**Comment by jarriztg** [comment]
Im using keyboards in this option:
```
echo 'OK. I will do a expression...'
echo 'Please, send me the first number.'
read A
echo 'OK. Now send me the second number.'
read B
echo 'What do you do? mykeyboardstartshere "Addition" "Subtraction" "Multiplication" "Division" "Cancel"'
read opt
 case $opt in
 'Addition') expr $A + $B ;;
 'Subtraction') expr $A - $B ;;
 'Multiplication') expr $A \* $B ;;
 'Division') expr $A / $B ;;
 'Cancel') exit ;;
esac
```

**Comment by jarriztg** [comment]
Starting with:
```
'/calc')
startproc "./filename"
;;
```

or maybe using this:

``` bash
'/calc')
send_markdown_message "${CHAT[ID]}" "*OK*. I will do a expression..."
send_markdown_message "${CHAT[ID]}" "Please, send me the first number."
read A
send_markdown_message "${CHAT[ID]}" "OK. Now send me the second number."
read B
send_markdown_message "${CHAT[ID]}" "What do you do?"
send_keyboard "${CHAT[ID]}" "Addition" "Subtraction" "Multiplication" "Division"'
read opt
 if [ $opt == 'Addition' then
  EXPR=$(expr $A + $B | bc)
  send_markdown_message "${CHAT[ID]}" "$EXPR"
 fi
 if [ $opt == 'Subtraction' then
  EXPR=$(expr $A - $B | bc)
  send_markdown_message "${CHAT[ID]}" "$EXPR"
 fi
 if [ $opt == 'Multiplication' then
 EXPR=$(expr $A \* $B | bc)
 send_markdown_message "${CHAT[ID]}" "$EXPR"
 fi
 if [ $opt == 'Division' then
  EXPR=$(expr $A / $B | bc)
  send_markdown_message "${CHAT[ID]}" "$EXPR"
fi
```

**Comment by gnadelwartz** [comment]
From Version 0.6 on it will be much easyer to define Keyboards, as we will use "Array Notation" as used by Telegram instead of relying on bashbot logic.

## Note on Keyboards
To make use of Keyboards easyer I changed the format of 'send_keyboard' and also of 'send_message "mykeyboardstartshere ..."'. Now you must provide  the keyboards in Telegram JSON style "[ \"yes\" , \"no\" ]".

The advantage is that you can create every type of keyboard without relying on bashbot ```send_keyboard``` functionality. **This is incompatible with keyboards in bashbot versions older than 0.6!**

*Example Keyboards*:

- Yes No in one row: "[ \"yes\" , \"no\" ]"
- Yes No ind two rows: "[ \"yes\" ] , [ \"no\" ]"
- numpad keyboard: "[ \"1\" , \"2\" , \"3\" ] , [ \"4\" , \"5\" , \"6\" ] , [ \"7\" , \"8\" , \"9\" ] , [ \"0\" ]"
