### ISSUE TITLE
Send files

### ISSUE THREAD

**Issue by Azat868** [topkecleon/telegram-bot-bash#43]
Please help me

**until [ "$SUCCESS" = "y" ] ;do
	echo 'Do you like Music? mykeyboardstartshere "Yass!" "No"'
	read answer
	case $answer in
		'Yass!') **echo "Text that will appear in chat? myfilelocationstartshere /home/user/myvideo.mp4"**;SUCCESS=y;;
		'No') echo "Well that's weird. mykeyboardendshere";SUCCESS=y;;
		*) SUCCESS=n;;
	esac**

Why it is not work?(

> Same goes for files:
> 
> echo "Text that will appear in chat? myfilelocationstartshere /home/user/doge.jpg"

**Comment by danog** [comment]
Please define "not work"; what error are you getting?

**Comment by Azat868** [comment]
good afternoon
Sorry for my English. I figured it out and solved the problem. It was necessary only to write
FILE_REGEX = ". *"

But now I have another problem. When I write any code in the cuestion, for example:

ffmpeg my.avi -f my.mov
![bot](https://user-images.githubusercontent.com/29046741/33649499-2a034f00-da6f-11e7-8f7b-9b84cc31cf8b.JPG)

then the bot sends me all the results of this command. How can I not display the execution of commands so that the bot does not send me the execution of the command?

**Comment by Azat868** [comment]
`> /dev/null 2>&1`

**Comment by danog** [comment]
Or even simpler, `&> /dev/null`
