### ISSUE TITLE
How to open menu

### ISSUE THREAD

**Issue by Azat868** [topkecleon/telegram-bot-bash#44]
![menu 2](https://user-images.githubusercontent.com/29046741/33663696-16d939b6-daa2-11e7-8996-605057b27537.JPG)
![menu](https://user-images.githubusercontent.com/29046741/33663697-16fe41fc-daa2-11e7-95b9-de2c84f89c5c.JPG)

**Comment by danog** [comment]
You must edit the command list in @botfather
