### ISSUE TITLE
Text shown as message and caption

### ISSUE THREAD

**Issue by Azat868** [topkecleon/telegram-bot-bash#45]
Good morning
Please tell me why Excellent sent 2 times. 1 time as just a message, the second time as a picture caption?
Thx you

![1x](https://user-images.githubusercontent.com/29046741/33701280-334af714-db2f-11e7-9f93-e21f19ac0e20.JPG)
![2x](https://user-images.githubusercontent.com/29046741/33701281-3369da94-db2f-11e7-8e73-5d54b6d0cf98.JPG)

**Comment by gnadelwartz** [comment]
what do you expect in your case:

1. excellent and picture as seperated messages?
2. picture with caption excellent?

IMHO it should be case 2 because its in one response

**Comment by gnadelwartz** [comment]
Ist fixed now, text is no more used as caption for file/picture: https://github.com/topkecleon/telegram-bot-bash/commit/ba80ec69766f87090216a041f43f2cb84d4c88d8
