### ISSUE TITLE
Access control for users

### ISSUE THREAD

**Issue by Azat868** [topkecleon/telegram-bot-bash#46]
Good morning
How do I access a bot for limited users? 
Do I have to do ${USER[ID]} a comparison in the file command.sh and start startproc "./question?
Thx you

**Comment by Alferez** [comment]
I put this code at start into commands.sh

grep "^${CHAT[ID]};" ./Valid_Users.txt
if [[ "$? " -eq 1 ]]
then
	exit
fi

**Comment by amontigita** [comment]
better use: 
grep -w
otherwise it will find subsets included in CHAT_ID to be true

**Comment by gnadelwartz** [comment]
Are you asking for limit some commands to a certain group of Users, e.g. Admin?
or a more general function to check against a list of users?

**Comment by amontigita** [comment]
My case is the second, limited list of users.

**Comment by gnadelwartz** [comment]
Im going to inplement the following functions in for 0.60:

- is_botadmin
- is_chatadmin
- is_ allowed "command"

to check if user is owner of the bot, is creator or admin of chat or is allowed to execute command

**Comment by gnadelwartz** [comment]
Its implemented in the develop tree: https://github.com/topkecleon/telegram-bot-bash/tree/develop and will be merged as 0.52 to master if no problems are found ... @Azat868 pls test ...
