### ISSUE TITLE
problem imoji and arabic text

### ISSUE THREAD

**Issue by momohammadi** [topkecleon/telegram-bot-bash#50]
huge problem , cant receive or send any emoji or arabic text from or to bot

**Comment by gnadelwartz** [comment]
have the same (and other) problems, but does not find the source.
For me the it looks like non ascii characters may not work and can result in output no message at all.

**Comment by momohammadi** [comment]
> have the same (and other) problems, but does not find the source.
> For me the it looks like non ascii characters may not work and can result in output no message at all.

i solve this problem with use this solution : 
1 : use an editor same as notepad++ 
2 : create a function for send message e.x:
```
sendMessage(){
        resId = $1
	message=$2	
		./bashbot.sh "frombash" "$resId " "mytext" "$message"
}
```
2 :  edit bashbot.sh file and add new case after "kill") with bellow content : 
`
	"frombash")
		CHAT[ID]=$2
		TYPE=$3
		MESSAGE=$4		
		FILE=$5
		if [ $TYPE = "mytext" ];then
			send_action "${CHAT[ID]}" "typing"
			send_markdown_message "${CHAT[ID]}" "${MESSAGE}"
		elif [ $TYPE = "myfile" ];then
			send_file "${CHAT[ID]}" "${FILE}" "${MESSAGE}"
		fi
		;;
`
3 : for send message  
`
         chatId = 249816XXX #telecgram user id
	 message="
	  * 📣📣 new event System Task 📣📣 *
	  
	  * 🔎 status : *  $status 
	  * ✏️ created by : * $auName
	  * ♨️ priority : * $priority
	  * 📆 create on : * $createDate
	  * ⏰ update on : * $updateDate
	  * ⏳ due date : * $dueDate
	  * 📉 done : * $percentDone% 
	  * 👁 assigned to : * $asName
	  * ⚠️ responsible : * $resName	  
	  * 📂 project : * $project
	  * 📝 task subject : * $subject
	  * 📃 short content : *  $shortcontent 
	 "
	 fi
	 sendMessage $chatId "$message"
`
Note :  most use a editore out of putty or terminal , same as notepad++ 

with this solution all emoji and arabic charecter send successfully

**Comment by gnadelwartz** [comment]
the general problem is that all programs ans commands used has to know how to handle utf-8 characters. 

bashbot itself is UTF-8 save in the sense that it can recieve and send utf-8 characters if the string is correctly encoded. the problem is the processing / altering the strings in custom commands.

1. your bash envuronment has to be set to utf-8: export LANG=C.UTF-8
2. as @momohammadi statet you have to use an UTF-8 aware editor
3. all commands used to manipulate strings has to be utf-8 aware

a more general solution may be to convert MESSAGE to ASCII with escaped non ASCII Characters, the do the processing and convert the result back to UTF-8

**Comment by gnadelwartz** [comment]
I dived a little more into the topic. one part of the problem is that json encodes most non ASCII characters as \uxxxx and send_text functions send them back as text.

An other part seems to be that sending messages containing non ASCII characters sometimes fail.

**Comment by gnadelwartz** [comment]
I investigated a little in the Problem:

- if I echo emojis (utf-8 >256) telegram reports "no utf-8 character"
- echoing of Umlaute (äöü utf-8 <256) works ok
- output of "correct" utf-8 >256 in a hand crafted string works in general

looks like a utf-8 conversion issue, charset mismatch

l see some possible reasons for this:

- echo -e does not wirk correct for json \unnnn to utf-8  for >256
- Message is recived as json but sent as url-encoded get request
- character encoding in json depends on language of User/Client, de in my case, resulting in a mismatch of received and sent characters.

**Comment by gnadelwartz** [comment]
after some research on stackoverflow it semms to be an incompatibility between json encoding if multibyte characters and echo -e, see https://stackoverflow.com/questions/8795702/#8831863

JSON will encode one code-point using two \u escapes, If you assume 1 escape sequence translates to 1 code point, you're doomed on such text.

An example that will break most attemps to convert json to utf-8 in bash is "\ud83d\udca3" (bomb)
```bash
% printf '"\\ud83d\\udca3"' | python2 -c 'import json, sys; sys.stdout.write(json.load(sys.stdin)[0].encode("utf-8"))'; echo
💣
# echo will result in corrupt output:
% echo -e $(printf '"\\ud83d\\udca3"') 
"������"
```

in the next dev3 branch I'll test if the phyton solution will fix the problem

**Comment by gnadelwartz** [comment]
Finally I got correct UTF-8 decoding and output working in develop branch:
![image](https://user-images.githubusercontent.com/4593242/56079869-7e14a480-5dfa-11e9-9410-73e3944da461.png)
 
This is done by using python JSON module. to not create a new dependency I implemented a fallback to old behaivor if no python is installed:
```
# use phyton to decode UFT-8 JSON, provide error prone echo -e as fallback
if which python >/dev/null 2>&1 || which phyton2 >/dev/null 2>&1; then
    jsondecode() {
        printf '"%s\\n"' "${1//\"/\\\"}" | python -c 'import json, sys; sys.stdout.write(json.load(sys.stdin).encode("utf-8"))'
    }
else
    echo -e "${ORANGE}WARNING: Fallback to non UTF mode, install python to have full UTF-8 support!${NC}"
    jsondecode() {
        echo -e "$1"
    }
fi
```
