### ISSUE TITLE
timed broadcast

### ISSUE THREAD

**Issue by RanjidTatu** [topkecleon/telegram-bot-bash#51]
Is it possible to send broadcasts to a specific day time? If so how?

greetings,
Ranjid

**Comment by gnadelwartz** [comment]
what about creating a script and using cron?

**Comment by RanjidTatu** [comment]
Thx for the answer but I tried it and it din't worked.

Maybe I had a mistake in the script or so

**Comment by gnadelwartz** [comment]
since I also want to implement timed actions, e.g. restart background scripts every day, I'll provide a example cron tab soon

**Comment by gnadelwartz** [comment]
give it a try with  PR #56 and #60
