### ISSUE TITLE
should we warn or fail if bashbot is run as root?

### ISSUE THREAD

**Issue by gnadelwartz** [topkecleon/telegram-bot-bash#57]
It's a high risk if a script processing user input is run with root privilegs.
I propose to at least output a warning if bashbot is running as UID 0

What's your opionon?

**Comment by topkecleon** [comment]
A warning at launch would be fine. Causing it to fail would be an antifeature.

**Comment by gnadelwartz** [comment]
ok, i'll add a warning at startup ...

**Comment by gnadelwartz** [comment]
implemented
