### ISSUE TITLE
Correctly decode all JSON Stings

### ISSUE THREAD

**Issue by gnadelwartz** [topkecleon/telegram-bot-bash#72]
**Describe the bug**
JSON stings contain "non ACSCII" characters endoded as ```\nnnnn``` for MESSAGE this is fixed now, but names etc. can also contain non ASCII.

**Expected behavior**
All strings extracted from JSON should be correct UTF-8 decoded by jsondecode() ...

Related to #50

**Comment by gnadelwartz** [comment]
If you like that bashbot is now able to decode JSON data correct, pls [upvote on stackoverflow](https://stackoverflow.com/questions/8795702/#55666449)

@danog @topkecleon @rostovtsev @swelljoe

**Comment by gnadelwartz** [comment]
done with https://github.com/topkecleon/telegram-bot-bash/commit/aa1404d49c21660299404bd121f1d18cb730fb11

**Comment by BondarenkoArtur** [comment]
I'm using `bot-bash` on router, so there is no python in it, but I need it to work properly.
I've patched one util to be able to use it in by piping some data in it.
Looks like it returns the same as python, but written simply and in C.
https://github.com/BondarenkoArtur/unescape

Also, maybe make sense to rewrite algorithm to bash.

**Comment by gnadelwartz** [comment]
nice, you use the same utf-8 sequence :) as demo. is your tool in your routers path? if yes we can modify the phyton test to test for your tool ...

**Comment by BondarenkoArtur** [comment]
here is file [c.txt](https://github.com/topkecleon/telegram-bot-bash/files/3076753/c.txt) that I've received by 
`printf '%s' "${test}" | ./unescape_pipe > c.txt`
`😁 😘 ❤️ 😊 👍`
Here is what `cat -v c.txt` showing:
`M-pM-^_M-^XM-^A M-pM-^_M-^XM-^X M-bM-^]M-$M-oM-8M-^O M-pM-^_M-^XM-^J M-pM-^_M-^QM-^M%`  
`%` in the end, because there is no new line in `printf`

**Comment by BondarenkoArtur** [comment]
I think it would be great if you'll be able to port that C code to bash. I cannot do that because I'm just not so good in bash, unfortunately...

**Comment by gnadelwartz** [comment]
hm, porting to bash is hard, but maybe detect JSON two byte escape sequences and convert them to one multibyte escape sequence ...

**Comment by gnadelwartz** [comment]
I investigated a little mor on bash implementation of UTF-16 to UTF-8 conversion needed.

The math itself is doable, also in bash:
```bash
# :-) = \ud83d\ude00
# hex:  0xd83d 0xde00
#         W1     W2
U=(  ( (W1 & 0x3ff) <<10 ) | (W2 & 0x3ff) ) + 0x10000 
```

But it is error prone and iterating over each charatcer of a (long) string and doing complex math is horrible slow. It is also something bash is not designed for ... may be an more skilled bash expert prove me wrong :-)

**Comment by gnadelwartz** [comment]
Cant believe, but got it!
```bash
#!/bin/bash
#
# test for utf16 to utf8 math

    JsonDecode() {
        local out="$1"
        local remain=""
        local regexp='(.*)\\ud([0-9a-fA-F]{3})\\ud([0-9a-fA-F]{3})(.*)'
        while [[ "${out}" =~ $regexp ]] ; do
                local W1="$(( ( 0xd${BASH_REMATCH[2]} & 0x3ff) <<10 ))"
                local W2="$(( 0xd${BASH_REMATCH[3]} & 0x3ff ))"
                U="$(( (${W1} | ${W2}) + 0x10000 ))"
                remain="$(printf '\\U%8.8x' "${U}")${BASH_REMATCH[4]}${remain}"
                out="${BASH_REMATCH[1]}"
        done
        echo -e "${out}${remain}"
    }

JsonDecode "$1"
```
Some tests:
```bash
$ ./utf16-utf8.sh 'xxx \ud83d\udc25 xxxx'
xxx 🐥 xxxx

$ ./utf16-utf8.sh '\ud83d\udc25'
🐥

$ ./utf16-utf8.sh '\u00e4 \u00e0 \u00f6 \u00f4 \u00fc \u00fb \ud83d\ude03 \ud83d\ude1a \ud83d\ude01 \ud83d\ude02 \ud83d\udc7c \ud83d\ude49 \ud83d\udc4e \ud83d\ude45 \ud83d\udc5d \ud83d\udc28 \ud83d\udc25 \ud83d\udc33 \ud83c\udf0f \ud83c\udf89 \ud83d\udcfb \ud83d\udd0a \ud83d\udcec \u2615 \ud83c\udf51'
ä à ö ô ü û 😃 😚 😁 😂 👼 🙉 👎 🙅 👝 🐨 🐥 🐳 🌏 🎉 📻 🔊 📬 ☕ 🍑
```
performance for 100 strings with 25 UTF-16 characters: ~25s -> 0.025s per string -> 0.001s per UTF-16 character! 
```bash 
$ time for x in $(seq 1 100); do ./utf16-utf8.sh '\u00e4 \u00e0 \u00f6 \u00f4 \u00fc \u00fb \ud83d\ude03 \ud83d\ude1a \ud83d\ude01 \ud83d\ude02 \ud83d\udc7c \ud83d\ude49 \ud83d\udc4e \ud83d\ude45 \ud83d\udc5d \ud83d\udc28 \ud83d\udc25 \ud83d\udc33 \ud83c\udf0f \ud83c\udf89 \ud83d\udcfb \ud83d\udd0a \ud83d\udcec \u2615 \ud83c\udf51' >/dev/null ; done

real    0m2,195s
user    0m1,635s
sys     0m0,647s
```

**Comment by gnadelwartz** [comment]
and in develop https://github.com/topkecleon/telegram-bot-bash/commit/5787908d726c13ed486f031ec14d8518d5d68309 !!

**Comment by BondarenkoArtur** [comment]
@gnadelwartz 
`"Y\u043Eu \u042F\u043E\u0441ks! \uD83E\uDD18`

**Comment by gnadelwartz** [comment]
found a case problem with your string: "\uD83E\uDD18" - works now also with uppercase copied from web ;-)

./test.sh "Y\u043Eu \u042F\u043E\u0441ks! \uD83E\uDD18"
Yоu Яосks! 🤘

**Comment by BondarenkoArtur** [comment]
Maybe make sense to separate Decoder to another file or module?
