### ISSUE TITLE
Needed error message for wrong token

### ISSUE THREAD

**Issue by BondarenkoArtur** [topkecleon/telegram-bot-bash#73]
**Describe the bug**
In case it you typed wrong token bot just crashes without any understandable error.

**Expected behavior**
A clear and concise description of error that token is wrong.

**Bashbot (please complete the following information):**
 - Version [ v0.52-0-gdb7b19f ]
 - OS: [ Linux Akronite 2.6.36.4brcmarm #32 SMP PREEMPT Tue Dec 15 13:55:41 CST 2015 armv7l GNU/Linux ]
 - Shell [ version 5.0.2(1)-release (arm-openwrt-linux-gnu) ]

**Comment by gnadelwartz** [comment]
Good Idea! lets See how to implement this ...

**Comment by gnadelwartz** [comment]
```bash
$ ./bashbot.sh
ERROR: Can't connect to Telegram Bot! May be your TOKEN is invalid ...
```
Is this sufficient for you?

**Comment by gnadelwartz** [comment]
@BondarenkoArtur  just released rc2, give it a try ...
