### ISSUE TITLE
Running three copies simultaneously on the same server

### ISSUE THREAD

**Issue by Azat868** [topkecleon/telegram-bot-bash#89]
Its really? Run 3 or more cpoies at 1 vps?

**Comment by gnadelwartz** [comment]
you can run as many copies you like, also 3 :smile: 

- until V0.6 you need 3 seperate instlations on the same server, e.g. in ...
    - /user/home/azcat/telegram-bot-1
    - /user/home/azcat/telegram-bot-2
    - /user/home/azcat/telegram-bot-3

- from v0.7 on you (may) run [multiple bots from one installation](../doc/8_config.md)
