### ISSUE TITLE
make bashbot working with minimal external command Set

### ISSUE THREAD

**Issue by gnadelwartz** [topkecleon/telegram-bot-bash#97]
**Is your issue is related to a problem? Please describe.**
even if we claim "bash only implemenation" we use external programms, e.g. curl.

**Describe your idea or complaint**
In general its OK to use external programms from GNU environment. nevertheless we should restrict us to proramms provided by [busybox](https://busybox.net/downloads/BusyBox.html) and [toybox](https://landley.net/toybox/help.html) to be as portable as possible, e.g. embedded system.

**Todo:**
[✔️] Document allowed commands / reference to busybox
[✔️] check usage of non busybox / toybox commands
[ :heavy_check_mark: ] use wget if no curl is availible ...

**Comment by gnadelwartz** [comment]
[Bash Builtins](https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html)
[Busybox Builtins](https://busybox.net/downloads/BusyBox.html)

**Comment by gnadelwartz** [comment]
curl and tmux are now the only hard external depedencies ...

- curl can be replaced by wget or pure bash (if no https is needed) ...
- tmux is no more needed, but some work to remove

**Comment by leopucci** [comment]
I am having trouble on a busybox system. I can´t run the script.

BusyBox v1.24.2 (2018-10-12 14:46:27 CST) built-in shell (ash)

```
telegram-bot-bash]# ./bashbot.sh init
./bashbot.sh: line 79: syntax error: bad substitution
```

Am I doing something wrong?
Thanks

**Comment by gnadelwartz** [comment]
hi,

looks like your system usees ash, not bash:

built-in shell (ash)

what's the output of 'which bash' ?

**Comment by leopucci** [comment]
here it is.. 

I tryed running the command bash, then runing again but no luck. 
This is busybox. On the readme it suggests busybox but it seems not to work. 
Any hints? 

```
telegram-bot-bash]# which bash
/bin/bash

[Rancho /etc/storage/telegram-bot-bash]# bash


BusyBox v1.24.2 (2018-10-12 14:46:27 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.

telegram-bot-bash]# bash -c ./bashbot.sh
./bashbot.sh: line 79: syntax error: bad substitution
```

**Comment by gnadelwartz** [comment]
and what's the output of 'bash --version' ?

on what hardware / system are you trying to run bashbot?

**Comment by gnadelwartz** [comment]
as said as first guess, it looks like the system has no "real" bash, instead it run's ash:

```
[Rancho /etc/storage/telegram-bot-bash]# bash


BusyBox v1.24.2 (2018-10-12 14:46:27 CST) built-in shell (ash)
Enter 'help' for a list of built-in commands.
```

**Comment by gnadelwartz** [comment]
I did a little resaerch on this topic and found that ash does support almost any basic bash features except Arrays, which is exactly the problem in line 79.

thanks for pointing out, I'll update the readme that busybox bash substitute ash is not sufficient,
and make more clear you have to install a real bash.

**Comment by leopucci** [comment]
Ok
Thanks

Em qua, 23 de set de 2020 02:45, Kay Marquardt <notifications@github.com>
escreveu:

**Comment by gnadelwartz** [comment]
added  examples how to test for correct bash https://github.com/topkecleon/telegram-bot-bash/blob/master/doc/0_install.md#check-bash-installation
